### ISSUE TITLE
How come you guys never minified variable names?

### ISSUE THREAD

**Issue by jbrooksuk** [convergame/drawbacks#1]
http://convergame.github.io/drawbacks/js13k/js13k.js

You'd be able to save loads more space :)

**Comment by ojdon** [comment]
Just didn't have it in our gulp workflow. An oversight on my part, I guess.

**Comment by jbrooksuk** [comment]
Ok :)

**Comment by Jord-JD** [comment]
Doh, that would have been a good one to save a few bytes. Ah well!

**Comment by Jord-JD** [comment]
Actually, if you take a look closely some of the variables in our code have actually minified.

It seems class names, methods and member variables have not been minified though, which is odd.
